services:
  micro-arquivos:
    build: .
    image: taohans/gestaocerta:micro-arquivos
    container_name: micro-arquivos
    depends_on:
      - mongodb
    environment:
      - APP_PROFILE=dev
      - SERVER_PORT=8082
      - GATEWAY_URL=http://localhost:8080/arq/
      - SPRING_DATA_MONGODB_URI=mongodb://root:root@mongodb:27017/db_arquivos?authSource=admin
    networks:
      - gestaocerta-private
      - int-arquivos-net

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-data:/data/db
    networks:
      - int-arquivos-net

networks:
  gestaocerta-private:
    external: true
  int-arquivos-net:

volumes:
  mongo-data:
    driver: local